//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Docking_MES_App.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReference1.ZWS_MZ")]
    public interface ZWS_MZ {
        
        // CODEGEN: 操作 ZFUN_MZ 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_MZ:ZFUN_MZRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1 ZFUN_MZ(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_MZ:ZFUN_MZRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1> ZFUN_MZAsync(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFUN_MZ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fCODEField;
        
        private string iNPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FCODE {
            get {
                return this.fCODEField;
            }
            set {
                this.fCODEField = value;
                this.RaisePropertyChanged("FCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string INPUT {
            get {
                return this.iNPUTField;
            }
            set {
                this.iNPUTField = value;
                this.RaisePropertyChanged("INPUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFUN_MZResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oUTPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OUTPUT {
            get {
                return this.oUTPUTField;
            }
            set {
                this.oUTPUTField = value;
                this.RaisePropertyChanged("OUTPUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFUN_MZRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAP_Docking_MES_App.ServiceReference1.ZFUN_MZ ZFUN_MZ;
        
        public ZFUN_MZRequest() {
        }
        
        public ZFUN_MZRequest(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZ ZFUN_MZ) {
            this.ZFUN_MZ = ZFUN_MZ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFUN_MZResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse ZFUN_MZResponse;
        
        public ZFUN_MZResponse1() {
        }
        
        public ZFUN_MZResponse1(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse ZFUN_MZResponse) {
            this.ZFUN_MZResponse = ZFUN_MZResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_MZChannel : SAP_Docking_MES_App.ServiceReference1.ZWS_MZ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_MZClient : System.ServiceModel.ClientBase<SAP_Docking_MES_App.ServiceReference1.ZWS_MZ>, SAP_Docking_MES_App.ServiceReference1.ZWS_MZ {
        
        public ZWS_MZClient() {
        }
        
        public ZWS_MZClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_MZClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_MZClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_MZClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1 SAP_Docking_MES_App.ServiceReference1.ZWS_MZ.ZFUN_MZ(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest request) {
            return base.Channel.ZFUN_MZ(request);
        }
        
        public SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse ZFUN_MZ(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZ ZFUN_MZ1) {
            SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest inValue = new SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest();
            inValue.ZFUN_MZ = ZFUN_MZ1;
            SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1 retVal = ((SAP_Docking_MES_App.ServiceReference1.ZWS_MZ)(this)).ZFUN_MZ(inValue);
            return retVal.ZFUN_MZResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1> SAP_Docking_MES_App.ServiceReference1.ZWS_MZ.ZFUN_MZAsync(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest request) {
            return base.Channel.ZFUN_MZAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAP_Docking_MES_App.ServiceReference1.ZFUN_MZResponse1> ZFUN_MZAsync(SAP_Docking_MES_App.ServiceReference1.ZFUN_MZ ZFUN_MZ) {
            SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest inValue = new SAP_Docking_MES_App.ServiceReference1.ZFUN_MZRequest();
            inValue.ZFUN_MZ = ZFUN_MZ;
            return ((SAP_Docking_MES_App.ServiceReference1.ZWS_MZ)(this)).ZFUN_MZAsync(inValue);
        }
    }
}
